### ISSUE TITLE
Make plugin installable through Composer

### ISSUE THREAD

**Issue by peter-sition** [RESPONSEGmbH/shopware_plugin_reschannable#1]
We would like to use this plugin as a composer dependency.
With the composer version of Shopware (https://github.com/shopware/composer-project) it is easy to install plugin through the composer.json file.

The main issues to get this working with the existing code:
- Move the code from `custom/plugins/resChannable` to the root of the repository
- Add a `composer.json` file. Important in this case is to add the `type` variabel with the value `shopware-plugin`. This section ensures that the plugin will be installed as a Shopware Plugin.

```json
{
  "name": "RESPONSEGmbH/shopware_plugin_reschannable",
  "description": "Channelable Plugin for Shopware",
  "homepage": "https://www.yourwebsite.com",
  "type": "shopware-plugin",
   [....]
}
```

**Comment by RESPONSE-GmbH** [comment]
Thank you for your suggestion. I will implement that in a future version.

**Comment by RESPONSE-GmbH** [comment]
For some time the plugin is available in the Shopware store. We recommend installation via the store.
Was this helpful to you?
